### ISSUE TITLE
wait what is this app written in again? 

### ISSUE THREAD

**Issue by ghost** [flyingcakes85/crabfetch#6]
hard to udnerstand

**Comment by flyingcakes85** [comment]
From my preliminary investigation, it seems like this application is written in the Rust programming language. It is blazing fast, post modern, correct, better than whatever GoLang can do, most memory safe app ever and next gen.


![image](https://github.com/flyingcakes85/crabfetch/assets/48585950/bdca05a0-8e5c-40a2-9acc-f636fb472b0f)

**Comment by ghost** [comment]
thank :3 s
